kafka-topics:
  resignation:
    event:
      name: jdmik11.resignation.event
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2
  accounting:
    command:
      name: jdmik11.accounting.command
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2
  security:
    command:
      name: jdmik11.security.command
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2

kafka-routes:
  accounting: ${kafka-topics.accounting.command.name}
  security: ${kafka-topics.security.command.name}
  resignation: ${kafka-topics.resignation.event.name}