spring:
  kafka:
    bootstrap-servers: localhost:9093,localhost:9095,localhost:9097

kafka-topics:
  resignation:
    event:
      name: jdmik11.resignation.event
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2
  accounting:
    command:
      name: jdmik11.accounting.command
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2
  security:
    command:
      name: jdmik11.security.command
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2
  notification:
    command:
      name: jdmik11.notification.command
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2

kafka-routes:
  routes:
    accounting: ${kafka-topics.accounting.command.name}
    security: ${kafka-topics.security.command.name}
    resignation: ${kafka-topics.resignation.event.name}
    notification: ${kafka-topics.notification.command.name}